### model
model_name_or_path: /base/rd1/large_models/Hunyuan-MT-7B
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: targin_train_add
template: hunyuan
cutoff_len: 512
save_only_model: true
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /base/rd1/large_models/train_save/full/wmt_total/hy_targin_add/3e-5
logging_steps: 10
save_steps: 10000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 3.0e-5
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
